version: '3'
vars:
  MAELSTROM_BIN: './runtime/maelstrom/maelstrom'

tasks:
  setup:
    desc: 'Setup the project'
    cmds:
    - echo "Setting up the project..."
    - brew install openjdk graphviz gnuplot
    - mkdir -p ./runtime
    - curl -L https://github.com/jepsen-io/maelstrom/releases/download/v0.2.4/maelstrom.tar.bz2 | tar xj -C ./runtime
    - echo "Project setup complete."
  test-echo:
    desc: 'Run echo test'
    cmds:
    - go -C echo build -o ../runtime/builds/echo
    - "{{.MAELSTROM_BIN}} test -w echo --bin ./runtime/builds/echo --node-count 1 --time-limit 10"
  test-unique-ids:
    desc: "Run 'Unique IDs' test"
    cmds:
    - go -C unique-ids build -o ../runtime/builds/unique-ids
    - "{{.MAELSTROM_BIN}} test -w unique-ids --bin ./runtime/builds/unique-ids --node-count 1 --time-limit 10"
  test-broadcast-single-node:
    desc: "Run 'Broadcast' test"
    cmds:
    - go -C broadcast build -o ../runtime/builds/broadcast
    - "{{.MAELSTROM_BIN}} test -w broadcast --bin ./runtime/builds/broadcast --node-count 1 --time-limit 20 --rate 10"
  test-all:
    cmds:
    - task: test-echo
    - task: test-unique-ids
